### ISSUE TITLE
problem: missing deployed contracts address information

### ISSUE THREAD

**Issue by georgeciubotaru** [clearpool-finance/CPOOL#16]
```[tasklist]
### Tasks
- [x] add contracts in the development folder
- [x] cleanup branches (keep only the main branch)
- [x] cleanup branches (vesting-dapp) - keep only the main and new vesting branches
```

**Comment by Addis-Belete** [comment]
Log: Some branches are not deleted.
Cc: @georgeciubotaru
